# Required:
[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'leico/autodate.vim'

#カラースキーマ
[[plugins]]
repo = 'ofirgall/ofirkai.nvim'

# [[plugins]]
# repo = 'itchyny/lightline.vim'
# hook_add = '''
#   let g:lightline = {
#   \ 'colorscheme': 'wombat'
#   \ }
# '''

[[plugins]]
repo = 'vim-airline/vim-airline'

[[plugins]]
repo = 'vim-airline/vim-airline-themes'
hook_add = '''
let g:airline_theme = 'wombat'               " テーマの指定
let g:airline#extensions#tabline#enabled = 1 " タブラインを表示
let g:airline_powerline_fonts = 1            " Powerline Fontsを利用
nmap <C-n> <Plug>AirlineSelectPrevTab
nmap <C-p> <Plug>AirlineSelectNextTab
'''

[[plugins]]
repo = 'ya2s/nvim-cursorline'
hook_add = '''
lua << EOF
require('nvim-cursorline').setup {
  cursorline = {
    -- Lineハイライトは動作が遅いためOFF
    enable = false,
    -- timeout = 1000,
    -- number = false,
  },
  cursorword = {
    enable = true,
    min_length = 3,
    hl = { underline = true },
  }
}
EOF
'''


# "gcc"でコメントアウト
# [[plugins]]
# repo = 'tpope/vim-commentary'

# インデント表示
[[plugins]]
repo = 'lukas-reineke/indent-blankline.nvim'
hook_add = '''
lua << EOF
require("ibl").setup()
EOF
'''

# Nerd fonts
[[plugins]]
repo='ryanoasis/vim-devicons'

# ddu.vim------------------
[[plugins]]
repo = 'vim-denops/denops.vim' # required by ddu.vim and ddc.vim

# [[plugins]]
# repo = 'Shougo/ddu.vim'
# hook_add= '''
#   call ddu#custom#patch_global({
#     \   'ui': 'ff',
#     \   'sources': [{'name':'file','params':{}},
#     \     {'name':'file_rec','params':{'ignoredDirectories': [".git","venv","__pycache__","build"]}},
#     \     {'name':'file_old','params':{}},
#     \     {'name':'register'},
#     \     {'name':'buffer'}],
#     \   'sourceOptions': {
#     \     '_': {
#     \       'matchers': ['matcher_fzf'],
#     \       'sorters': ['sorter_fzf'],
#     \     },
#     \   },
#     \   'kindOptions': {
#     \     'file': {
#     \       'defaultAction': 'open',
#     \     }
#     \   },
#     \   'filterParams': {
#     \     'matcher_fzf': {
#     \       'highlightMatched': 'Search',
#     \     },
#     \   }
#     \ })
#
#   "ddu key mapping
#   nnoremap <silent> <C-f> :<C-u>Ddu file<CR>
#   nnoremap <silent> <C-u> :<C-u>Ddu file_rec<CR>
#   "nnoremap <silent> <C-r> :<C-u>Ddu file_old<CR>
#   nnoremap <silent> <C-b> :<C-u>Ddu buffer<CR>
# '''
#
# [[plugins]]
# # 基本のUI
# repo = 'Shougo/ddu-ui-ff'
# hook_add = '''
#   autocmd FileType ddu-ff call s:ddu_my_settings()
#   function! s:ddu_my_settings() abort
#     nnoremap <buffer><silent> <CR>
#           \ <Cmd>call ddu#ui#do_action('itemAction')<CR>
#     nnoremap <buffer><silent> <Space>
#           \ <Cmd>call ddu#ui#do_action('toggleSelectItem')<CR>
#     nnoremap <buffer><silent> i
#           \ <Cmd>call ddu#ui#do_action('openFilterWindow')<CR>
#     nnoremap <buffer><silent> q
#           \ <Cmd>call ddu#ui#do_action('quit')<CR>
#   endfunction
#
#   autocmd FileType ddu-ff-filter call s:ddu_filter_my_settings()
#   function! s:ddu_filter_my_settings() abort
#     inoremap <buffer> <CR>
#     \ <Esc><Cmd>call ddu#ui#do_action('closeFilterWindow')<CR>
#     nnoremap <buffer> <CR>
#     \ <Esc><Cmd>call ddu#ui#do_action('closeFilterWindow')<CR>
#   endfunction
# '''
#
# [[plugins]]
# # ファイル用UI
# repo = 'Shougo/ddu-ui-filer'
# hook_add = '''
#   autocmd FileType ddu-filer call s:ddu_ui_filer_my_settings()
#   function! s:ddu_ui_filer_my_settings() abort
#     set modifiable
#     nnoremap <buffer><silent> <CR>
#     \ ddu#ui#filer#is_directory() ?
#     \ "<Cmd>call ddu#ui#filer#do_action('itemAction',{'name': 'narrow'})<CR>" :
#     \ "<Cmd>call ddu#ui#filer#do_action('itemAction',{'name': 'open'})<CR>"
#     nnoremap <buffer><silent> q
#     \ <Cmd>close<CR>
#   endfunction
# '''
#
# [[plugins]]
# # file open kind: ファイルオープン動作
# repo = 'Shougo/ddu-kind-file'
#
# # [[plugins]]
# # # 検索機能
# # repo = 'Shougo/ddu-filter-matcher_substring'
#
# [[plugins]]
# # ファジーファインダー
# repo = 'yuki-yano/ddu-filter-fzf'
#
# [[plugins]]
# # ファイル用ソース
# repo = 'Shougo/ddu-source-file'
#
# [[plugins]]
# # ファイルを再帰的に探すソース
# repo = 'Shougo/ddu-source-file_rec' # depends on ddu-kind-file"
#
# [[plugins]]
# # レジスタ用ソース
# repo = 'Shougo/ddu-source-register'
#
# [[plugins]]
# # 履歴用ソース
# repo = 'Shougo/ddu-source-file_old'
#
# [[plugins]]
# # バッファ用ソース
# repo = 'shun/ddu-source-buffer'
#
# [[plugins]]
# # # Ddu <file source>で実行できるようになる
# # # 一番最後に読み込む必要あり
# repo = 'Shougo/ddu-commands.vim'
#--------------------

# snacks.nvim------------------
[[plugins]]
repo = 'folke/snacks.nvim'
hook_add = '''
lua << EOF
require("snacks").setup({
  picker = { enabled = true },
  explorer = { enabled = true },
})
local snacks_exclude = { ".git", "venv", "__pycache__", "build" }
vim.keymap.set("n", "<C-f>",      function() Snacks.picker.files({ exclude = snacks_exclude }) end, { silent = true })
vim.keymap.set("n", "<C-u>",      function() Snacks.picker.files({ exclude = snacks_exclude, hidden = true, ignored = true }) end, { silent = true })
vim.keymap.set("n", "<C-b>",      function() Snacks.picker.buffers() end, { silent = true })
vim.keymap.set("n", "<leader>fb", function() Snacks.picker.buffers() end, { desc = "Buffers", silent = true })
vim.keymap.set("n", "<leader>fc", function() Snacks.picker.files({ cwd = vim.fn.stdpath("config") }) end, { desc = "Find Config File", silent = true })
vim.keymap.set("n", "<leader>ff", function() Snacks.picker.files() end, { desc = "Find Files", silent = true })
vim.keymap.set("n", "<leader>fg", function() Snacks.picker.git_files() end, { desc = "Find Git Files", silent = true })
vim.keymap.set("n", "<leader>fp", function() Snacks.picker.projects() end, { desc = "Projects", silent = true })
vim.keymap.set("n", "<leader>fr", function() Snacks.picker.recent() end, { desc = "Recent", silent = true })
vim.keymap.set("n", "<leader>sb", function() Snacks.picker.lines() end, { desc = "Buffer Lines", silent = true })
vim.keymap.set("n", "<leader>sB", function() Snacks.picker.grep_buffers() end, { desc = "Grep Open Buffers", silent = true })
vim.keymap.set("n", "<leader>sg", function() Snacks.picker.grep() end, { desc = "Grep", silent = true })
vim.keymap.set({ "n", "x" }, "<leader>sw", function() Snacks.picker.grep_word() end, { desc = "Visual selection or word", silent = true })
vim.keymap.set("n", "<leader>e", function() Snacks.explorer() end, { desc = "File Explorer", silent = true })
EOF
'''
